// components/media-bar/lightbox/item/item.component.ts
import { Component, Input, Inject, SkipSelf, OnChanges, SimpleChanges, OnInit } from '@angular/core';
import { MediaBarComponent } from '../../media-bar.component';
import { MediaBarLightboxComponent, MediaBarLightboxConfig } from '../lightbox.component';
import template from 'html!./item.component.html';

@Component({
	selector: 'gj-media-bar-lightbox-item',
	template,
})
export class MediaBarLightboxItemComponent implements OnInit, OnChanges
{
	@Input( '<' ) item: any;
	@Input( '<' ) itemIndex: number;
	@Input( '<' ) activeIndex: number;
	@Input( '<' ) mediaBar: MediaBarComponent;

	elem: HTMLElement;

	isActive = false;
	isNext = false;
	isPrev = false;

	maxWidth?: number;
	maxHeight?: number;

	constructor(
		// @Inject( '$window' ) private $window: ng.IWindowService,
		@Inject( '$timeout' ) private $timeout: ng.ITimeoutService,
		@Inject( '$scope' ) $scope: ng.IScope,
		@Inject( '$element' ) $element: ng.IAugmentedJQuery,
		@Inject( MediaBarLightboxComponent ) @SkipSelf() private lightbox: MediaBarLightboxComponent,
	)
	{
		this.elem = $element[0];
		$scope.$on( 'MediaBarLightbox.onResize', () => this.calcDimensions() );
	}

	ngOnInit()
	{
		this.calcActive();
		this.calcDimensions();
	}

	ngOnChanges( changes: SimpleChanges )
	{
		if ( changes['activeIndex'] ) {
			this.calcActive();
		}
	}

	play()
	{
		this.mediaBar.isPlaying = this.itemIndex;
	}

	calcDimensions()
	{
		this.maxWidth = this.lightbox.maxItemWidth - MediaBarLightboxConfig.itemPadding;
		this.maxHeight = this.lightbox.maxItemHeight;

		const captionElement = this.elem.getElementsByClassName( 'media-bar-lightbox-item-caption' )[0] as HTMLElement;
		if ( captionElement ) {
			this.maxHeight -= captionElement.offsetHeight;
		}

		if ( this.item.media_type == 'image' ) {
			const dimensions = this.item.media_item.getDimensions( this.maxWidth, this.maxHeight );
			this.maxWidth = dimensions.width;
			this.maxHeight = dimensions.height;
		}
	}

	calcActive()
	{
		this.isActive = this.activeIndex == this.itemIndex;
		this.isNext = this.activeIndex + 1 == this.itemIndex;
		this.isPrev = this.activeIndex - 1 == this.itemIndex;

		this.elem.classList.remove( 'active', 'next', 'prev' );

		if ( this.isActive ) {
			this.elem.classList.add( 'active' );
		}
		else if ( this.isPrev ) {
			this.elem.classList.add( 'prev' );
		}
		else if ( this.isNext ) {
			this.elem.classList.add( 'next' );
		}

		if ( this.isActive || this.isNext || this.isPrev ) {

			// Since changing these values affect whether or not the image is loaded (ng-if in the template)
			// we have to wait until angular compiles back in.
			this.$timeout( () => this.calcDimensions(), 0 );
		}
	}
}


<div class="media-bar-lightbox-item" ng-if="$ctrl.isActive || $ctrl.isNext || $ctrl.isPrev">
	<div class="media-bar-lightbox-item-inner" ng-switch="$ctrl.item.media_type">

		<!-- Image -->
		<div ng-switch-when="image">
			<div class="media-bar-lightbox-item-embed"
				ng-if="$ctrl.maxWidth && $ctrl.maxHeight"
				>

				<!--
					The min/max will be the actual dimensions for the image thumbnail.
				-->
				<img
					gj-img-responsive="{{ $ctrl.item.img_thumbnail }}"
					alt="{{ $ctrl.item.caption }}"
					ng-style="{ width: $ctrl.maxWidth + 'px', height: $ctrl.maxHeight + 'px' }"
					>
			</div>

			<div class="media-bar-lightbox-item-caption" ng-if="$ctrl.item.caption">
				<h4>{{ $ctrl.item.caption }}</h4>
			</div>
		</div>

		<!-- Video -->
		<div ng-switch-when="video">
			<div class="media-bar-lightbox-item-embed"
				ng-if="$ctrl.maxWidth && $ctrl.maxHeight"
				>
				<div ng-if="$ctrl.mediaBar.isPlaying != $ctrl.itemIndex ">

					<!--
						Since we don't have the original width/height for videos, we have to just set max dimensions for the thumbnail.
					-->
					<img
						gj-img-responsive="{{ $ctrl.item.img_thumbnail }}"
						alt="{{ $ctrl.item.title }}"
						ng-style="{ 'max-height': $ctrl.maxHeight + 'px', 'max-width': $ctrl.maxWidth + 'px' }"
						>

					<span class="play-button-overlay" ng-click="$ctrl.play()">
						<span class="jolticon jolticon-play"></span>
					</span>
				</div>

				<div ng-if="$ctrl.mediaBar.isPlaying == $ctrl.itemIndex">
					<gj-video-embed
						class="media-bar-lightbox-item-embed"
						video-provider="{{ $ctrl.item.type }}"
						video-id="$ctrl.item.url"
						max-video-width="$ctrl.maxWidth"
						max-video-height="$ctrl.maxHeight"
						autoplay="true"
						>
					</gj-video-embed>
				</div>
			</div>

			<div class="media-bar-lightbox-item-caption">
				<h4>{{ $ctrl.item.title }}</h4>
				<p ng-if="$ctrl.item.description" ng-bind-html="$ctrl.item.description | linky"></p>
			</div>
		</div>

		<!-- Sketchfab -->
		<div ng-switch-when="sketchfab">
			<div class="game-media-bar-lightbox-item-embed"
				ng-if="$ctrl.maxWidth && $ctrl.maxHeight"
				>
				<div ng-if="$ctrl.mediaBar.isPlaying != $ctrl.itemIndex ">

					<!--
						Since we don't have the original width/height for videos, we have to just set max dimensions for the thumbnail.
					-->
					<img
						ng-src="{{ $ctrl.item.img_thumbnail }}"
						alt=""
						ng-style="{ 'max-height': $ctrl.maxHeight + 'px', 'max-width': $ctrl.maxWidth + 'px' }"
						>

					<span class="play-button-overlay" ng-click="$ctrl.play()">
						<span class="jolticon jolticon-play"></span>
					</span>
				</div>

				<div ng-if="$ctrl.mediaBar.isPlaying == $ctrl.itemIndex">
					<gj-sketchfab-embed
						class="game-media-bar-lightbox-item-embed"
						[sketchfab-id]="$ctrl.item.sketchfab_id"
						[max-width]="$ctrl.maxWidth"
						[max-height]="$ctrl.maxHeight"
						[autoplay]="true"
						>
					</gj-sketchfab-embed>
				</div>
			</div>
		</div>

	</div>
</div>

// components/media-bar/lightbox/item/item.vue
<template>
	<div class="media-bar-lightbox-item">
		<div class="-inner" v-if="isActive || isNext || isPrev">
			<!-- Image -->
			<template v-if="item.media_type === 'image'">
				<div class="-embed">
					<!--
					The min/max will be the actual dimensions for the image thumbnail.
				-->
					<app-img-responsive
						:src="item.img_thumbnail"
						:alt="item.caption"
						:style="{
							width: maxWidth ? maxWidth + 'px' : undefined,
							height: maxHeight ? maxHeight + 'px' : undefined,
						}"
					/>
				</div>

				<div class="-caption" v-if="item.caption" ref="caption">
					<h4>{{ item.caption }}</h4>
				</div>
			</template>

			<!-- Video -->
			<template v-else-if="item.media_type === 'video'">
				<div class="-embed" v-if="isActive">
					<app-video-embed
						:video-provider="item.type"
						:video-id="item.url"
						:max-video-width="maxWidth"
						:max-video-height="maxHeight"
						:autoplay="true"
					/>
				</div>

				<div class="-caption" v-if="item.title || item.description" ref="caption">
					<h4>{{ item.title }}</h4>
					<!--TODO: This used to link links-->
					<p v-if="item.description" v-text="item.description"></p>
				</div>
			</template>

			<!-- Sketchfab -->
			<template v-else-if="item.media_type === 'sketchfab'">
				<div class="-embed" v-if="isActive">
					<app-sketchfab-embed
						:sketchfab-id="item.sketchfab_id"
						:max-width="maxWidth"
						:max-height="maxHeight"
						:autoplay="true"
					/>
				</div>
			</template>
		</div>
	</div>
</template>

<style src="./item.styl" scoped />

<script lang="ts" src="./item" />
